import type {
  Agent,
  Workflow,
  ExecutionDataPoint,
  Product,
  DashboardStat,
} from "@/types/dashboard";

export const mockAgents: Agent[] = [
  {
    id: "1",
    name: "Customer Support Bot",
    description: "Handles tier-1 customer inquiries",
    status: "active",
    model: "GPT-4o",
    lastRun: "2 min ago",
    successRate: 97.3,
  },
  {
    id: "2",
    name: "Data Pipeline Agent",
    description: "ETL processing and data validation",
    status: "active",
    model: "Claude 3.5",
    lastRun: "5 min ago",
    successRate: 99.1,
  },
  {
    id: "3",
    name: "Code Review Assistant",
    description: "Automated PR review and suggestions",
    status: "idle",
    model: "GPT-4o",
    lastRun: "1 hr ago",
    successRate: 94.8,
  },
  {
    id: "4",
    name: "Content Generator",
    description: "Blog and marketing content creation",
    status: "error",
    model: "Claude 3.5",
    lastRun: "15 min ago",
    successRate: 87.2,
  },
  {
    id: "5",
    name: "Sales Copilot",
    description: "Lead scoring and outreach drafting",
    status: "active",
    model: "GPT-4o",
    lastRun: "Just now",
    successRate: 95.6,
  },
  {
    id: "6",
    name: "Research Agent",
    description: "Market research and competitive analysis",
    status: "draft",
    model: "Claude 3.5",
    lastRun: "Never",
    successRate: 0,
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: "1",
    name: "Lead Qualification Pipeline",
    description: "Multi-step lead scoring flow",
    status: "active",
    nodeCount: 8,
    lastRun: "3 min ago",
    executionCount: 1247,
  },
  {
    id: "2",
    name: "Incident Response Chain",
    description: "Alert triage and escalation",
    status: "active",
    nodeCount: 12,
    lastRun: "10 min ago",
    executionCount: 892,
  },
  {
    id: "3",
    name: "Content Review Pipeline",
    description: "Multi-stage content approval",
    status: "inactive",
    nodeCount: 6,
    lastRun: "2 days ago",
    executionCount: 341,
  },
  {
    id: "4",
    name: "Onboarding Automation",
    description: "New user onboarding sequence",
    status: "active",
    nodeCount: 10,
    lastRun: "30 min ago",
    executionCount: 2103,
  },
  {
    id: "5",
    name: "Data Sync Workflow",
    description: "Cross-platform data synchronization",
    status: "draft",
    nodeCount: 4,
    lastRun: "Never",
    executionCount: 0,
  },
];

export const mockExecutionData: ExecutionDataPoint[] = [
  { date: "Mar 28", success: 95, failed: 8 },
  { date: "Mar 29", success: 102, failed: 5 },
  { date: "Mar 30", success: 88, failed: 12 },
  { date: "Mar 31", success: 110, failed: 6 },
  { date: "Apr 01", success: 97, failed: 9 },
  { date: "Apr 02", success: 115, failed: 4 },
  { date: "Apr 03", success: 108, failed: 7 },
];

export const mockProducts: Product[] = [
  {
    id: "ai-engine",
    title: "AI Engine",
    description: "Build Intelligent AI Agents",
    href: "/ai-engine",
    gradient: "from-rose-500 to-orange-500",
    iconBg: "bg-rose-500/10 dark:bg-rose-500/20",
  },
  {
    id: "legal-ops",
    title: "Legal Ops",
    description: "Intelligent Contract Lifecycle Management",
    href: "#",
    gradient: "from-teal-500 to-cyan-500",
    iconBg: "bg-teal-500/10 dark:bg-teal-500/20",
  },
  {
    id: "analytics",
    title: "Analytics",
    description: "Turn Data Into Actionable Insights",
    href: "#",
    gradient: "from-violet-500 to-indigo-500",
    iconBg: "bg-violet-500/10 dark:bg-violet-500/20",
  },
  {
    id: "autoscan",
    title: "AutoScan",
    description: "Automate Document Processing",
    href: "#",
    gradient: "from-cyan-500 to-blue-500",
    iconBg: "bg-cyan-500/10 dark:bg-cyan-500/20",
  },
  {
    id: "deal-room",
    title: "Deal Room",
    description: "Secure Virtual Data Room for Transactions",
    href: "#",
    gradient: "from-amber-500 to-orange-500",
    iconBg: "bg-amber-500/10 dark:bg-amber-500/20",
  },
];

export const mockDashboardStats: DashboardStat[] = [
  {
    title: "Active Contracts",
    value: "1,234",
    change: 12,
    gradient: "from-indigo-500 to-violet-500",
    iconBg: "bg-indigo-500/10 dark:bg-indigo-500/20",
  },
  {
    title: "Team Members",
    value: 48,
    change: 5,
    gradient: "from-teal-500 to-cyan-500",
    iconBg: "bg-teal-500/10 dark:bg-teal-500/20",
  },
  {
    title: "Avg. Processing",
    value: "2.4h",
    change: -18,
    gradient: "from-amber-500 to-orange-500",
    iconBg: "bg-amber-500/10 dark:bg-amber-500/20",
  },
  {
    title: "Completed",
    value: 892,
    change: 24,
    gradient: "from-emerald-500 to-teal-500",
    iconBg: "bg-emerald-500/10 dark:bg-emerald-500/20",
  },
];
